version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
